### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by hadix-lin** [Abnaxos/pegdown-doclet#72] opened 2016-10-19 07:27 UTC
Assertion failed
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:156)
    at com.intellij.openapi.diagnostic.Logger.assertTrue(Logger.java:165)
    at com.intellij.psi.impl.source.PsiParameterListImpl.getParameterIndex(PsiParameterListImpl.java:50)
    at com.intellij.psi.util.PsiFormatUtil.getExternalName(PsiFormatUtil.java:453)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.getExternalName(BaseExternalAnnotationsManager.java:80)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.a(BaseExternalAnnotationsManager.java:208)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.a(BaseExternalAnnotationsManager.java:146)
    at com.intellij.codeInsight.BaseExternalAnnotationsManager.findExternalAnnotations(BaseExternalAnnotationsManager.java:123)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.a(JavaDocInfoGenerator.java:912)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.a(JavaDocInfoGenerator.java:1052)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfoCore(JavaDocInfoGenerator.java:395)
    at com.intellij.codeInsight.javadoc.JavaDocInfoGenerator.generateDocInfo(JavaDocInfoGenerator.java:436)
    at com.intellij.lang.java.JavaDocumentationProvider.generateExternalJavadoc(JavaDocumentationProvider.java:554)
    at com.intellij.lang.java.JavaDocumentationProvider.generateDoc(JavaDocumentationProvider.java:542)
    at ch.raffael.doclets.pegdown.integrations.idea.PegdownDocumentationProvider.generateDoc(PegdownDocumentationProvider.java:134)
    at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:144)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:669)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:848)
    at com.intellij.codeInsight.navigation.CtrlMouseHandler.a(CtrlMouseHandler.java:666)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:222)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
    at com.intellij.util.Alarm$Request.run(Alarm.java:389)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
    at com.intellij.util.concurrency.BoundedTaskExecutor.runFirstTaskThenPollAndRunRest(BoundedTaskExecutor.java:178)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$000(BoundedTaskExecutor.java:40)
    at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:197)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Skamandros** [comment] 2016-12-05 15:25
I'm receiving this exception too from time to time. However, I wasn't able to determine when exactly it is thrown and it doesn't seem to cause any limited functionality, but I'll try to keep an eye on it.

**Comment by Abnaxos** [comment] 2017-01-08 09:57
Duplicate of #52.

**Closed by Abnaxos** 2017-01-08 09:57 UTC
